Traceback (most recent call last):
  File "/Users/xaru/work/python/temp/lib/python3.6/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/Users/xaru/work/python/temp/lib/python3.6/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/xaru/work/python/temp/lib/python3.6/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/xaru/work/python/temp/lib/python3.6/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/xaru/.pyenv/versions/3.6.5/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/Users/xaru/work/python/temp/lib/python3.6/site-packages/nbclient/client.py", line 541, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/Users/xaru/work/python/temp/lib/python3.6/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/xaru/work/python/temp/lib/python3.6/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import spacy
nlp = spacy.load("en_core_web_sm", exclude=["ner", "senter"])
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[0;32m<ipython-input-1-aa4c61613960>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0;32mimport[0m [0mspacy[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0mnlp[0m [0;34m=[0m [0mspacy[0m[0;34m.[0m[0mload[0m[0;34m([0m[0;34m"en_core_web_sm"[0m[0;34m,[0m [0mexclude[0m[0;34m=[0m[0;34m[[0m[0;34m"ner"[0m[0;34m,[0m [0;34m"senter"[0m[0;34m][0m[0;34m)[0m[0;34m[0m[0m

[0;31mModuleNotFoundError[0m: No module named 'spacy'
ModuleNotFoundError: No module named 'spacy'

